### ISSUE TITLE
Support edge bundling (tracking)

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#121]
#### What is edge bundling?

Instead of bundling & minifying in CI ahead of time, do it lazily in the HTTP request just before it's sent to the client, then cache it at the edge. "edge bundling" is a phrase I made up

Bun is fast enough to support this, but more infra needs to be built to make it good.

- [x] Port esbuild's JavaScript minifier to bun's JavaScript parser
- [x] Port esbuild's CSS parser to bun (including the minifier)
- [x] Implement tree-shaking
- [x] Implement code splitting
- [ ] Revise .bun format to support partially bundled code, or just get rid of it entirely.
- [x] Implement sourcemaps
- [ ] Expose all this in a WASM build that can be used in environments like Cloudflare Workers

**Comment by burdiyan** [comment]
For many years I've been wonder why nobody does it this way. Finally found a proof that I wasn't crazy :)

**Comment by Jarred-Sumner** [comment]
We're probably not going to do this exactly, but we do support most of this nowadays anyway when [bundling in `Bun.serve()`](https://bun.sh/docs/bundler/fullstack)
