### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#13830]
- [x] test/js/node/process/process.test.js - @190n https://github.com/oven-sh/bun/pull/13842
- [ ] test/cli/watch/watch.test.ts - @dylanconway
- [ ] test/cli/hot/watch.test.ts - @dylanconway
- [x] test/cli/hot/hot.test.ts - @dylanconway
- [x] test/integration/expo-app/expo.test.ts - @dylanconway
- [ ] test/cli/install/registry/bun-install-registry.test.ts - @dylanconway
- [x] test/napi/napi.test.ts - @190n #13831 
- [x] test/js/bun/spawn/spawn-streaming-stdin.test.ts - @190n #13860
- [x] test/regression/issue/07500/07500.test.ts - @190n #13900
- [x] test/js/bun/shell/shell-hang.test.ts - @190n #13932
- [ ] test/js/third_party/mongodb/mongodb.test.ts - @190n
- [ ] test/bundler/bun-build-api.test.ts - @dylanconway
- [ ] test/js/web/streams/streams.test.js - SKIP
- [ ] test/js/bun/http/bun-serve-static.test.ts - ??
- [ ] test/js/bun/http/serve-body-leak.test.ts - ??
- [ ] test/js/bun/http/fetch-file-upload.test.ts - @190n
- [x] test/js/web/timers/setInterval.test.js -  @190n #13929
- [ ] test/js/node/fs/fs.test.ts - @190n
- [ ] test/js/web/fetch/fetch.test.ts - ??
- [ ] test/js/web/fetch/fetch-tcp-stress.test.ts - ??
- [x] test/napi/napi.test.ts again - @190n #13955
