### ISSUE TITLE
MVP of CSS parser

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#14167]
In [#14122](https://github.com/oven-sh/bun/pull/14122), we've added a new CSS parser to Bun (a Zig port of [LightningCSS](https://github.com/parcel-bundler/lightningcss), huge thanks to Devon Govett, the LightningCSS contributors, and the Servo contributors)

This issue is meant to track the work towards getting the CSS parser fully usable in `bun build`, `Bun.build`, and Bun Kit. It will be closed when these features are implemented and tested.

## Integration into `bun build`

- [x] Support `Bun.build` API
- [x] Support `bun build --no-bundle`
- [x] Support `bun build`
- [x] Support `bun build` with `--minify`

## Features to implement

- [ ] Sourcemaps (needs integration with `bun build` and `Bun.build` as well)
- [ ] `@import` must resolve files and integrate with the module resolver, using `bun.ImportKind` and work with Bun.build plugins
- [ ] `url()` must resolve files and integrate with the module resolver
- [x] Nesting rules

### Minification pass

- [ ] `media`
- [ ] `import`
- [ ] `style`
- [ ] `keyframes`
- [ ] `font-face`
- [ ] `font-palette-values`
- [ ] `page`
- [ ] `supports`
- [ ] `counter-style`
- [ ] `namespace`
- [ ] `moz-document`
- [ ] `nesting`
- [ ] `viewport`
- [ ] `custom-media`
- [ ] `layer-statement`
- [ ] `layer-block`
- [ ] `property`
- [ ] `container`
- [ ] `scope`
- [ ] `starting-style`
- [ ] `unknown`
- [ ] `custom`

### Minify and downlevel properties
(210/292)
- [x] `-webkit-mask-composite`
- [ ] `accent-color`
- [x] `align-content`
- [x] `align-items`
- [x] `align-self`
- [ ] `animation-composition`
- [ ] `animation-delay`
- [ ] `animation-direction`
- [ ] `animation-duration`
- [ ] `animation-fill-mode`
- [ ] `animation-iteration-count`
- [ ] `animation-name`
- [ ] `animation-play-state`
- [ ] `animation-range-end`
- [ ] `animation-range-start`
- [ ] `animation-range`
- [ ] `animation-timeline`
- [ ] `animation-timing-function`
- [x] `aspect-ratio`
- [ ] `backdrop-filter`
- [ ] `backface-visibility`
- [x] `background-attachment`
- [x] `background-clip`
- [x] `background-color`
- [x] `background-image`
- [x] `background-origin`
- [x] `background-position-x`
- [x] `background-position-y`
- [x] `background-position`
- [x] `background-repeat`
- [x] `background-size`
- [x] `background`
- [x] `block-size`
- [x] `border-block-color`
- [x] `border-block-end-width`
- [x] `border-block-end`
- [x] `border-block-start-width`
- [x] `border-block-start`
- [x] `border-block-style`
- [x] `border-block-width`
- [x] `border-block`
- [x] `border-bottom-left-radius`
- [x] `border-bottom-right-radius`
- [x] `border-bottom-width`
- [x] `border-bottom`
- [x] `border-color`
- [x] `border-end-end-radius`
- [x] `border-end-start-radius`
- [x] `border-image-outset`
- [x] `border-image-repeat`
- [x] `border-image-slice`
- [x] `border-image-source`
- [x] `border-image-width`
- [x] `border-image`
- [x] `border-inline-color`
- [x] `border-inline-end-style`
- [x] `border-inline-end-width`
- [x] `border-inline-end`
- [x] `border-inline-start-style`
- [x] `border-inline-start-width`
- [x] `border-inline-start`
- [x] `border-inline-style`
- [x] `border-inline-width`
- [x] `border-inline`
- [x] `border-left-width`
- [x] `border-left`
- [x] `border-radius`
- [x] `border-right-width`
- [x] `border-right`
- [x] `border-start-end-radius`
- [x] `border-start-start-radius`
- [x] `border-style`
- [x] `border-top-left-radius`
- [x] `border-top-right-radius`
- [x] `border-top-width`
- [x] `border-top`
- [x] `border-width`
- [x] `border`
- [x] `box-align`
- [ ] `box-decoration-break`
- [x] `box-direction`
- [x] `box-flex-group`
- [x] `box-flex`
- [x] `box-lines`
- [x] `box-ordinal-group`
- [x] `box-orient`
- [x] `box-pack`
- [x] `box-shadow`
- [x] `box-sizing`
- [ ] `caret-color`
- [ ] `caret-shape`
- [ ] `clip-path`
- [ ] `clip-rule`
- [x] `color`
- [ ] `color-interpolation-filters`
- [ ] `color-interpolation`
- [ ] `color-rendering`
- [ ] `color-scheme`
- [x] `composes`
- [x] `column-gap`
- [ ] `container-name`
- [ ] `container-type`
- [x] `direction`
- [x] `display`
- [ ] `fill-opacity`
- [ ] `fill-rule`
- [x] `flex-align`
- [x] `flex-basis`
- [x] `flex-direction`
- [x] `flex-flow`
- [x] `flex-grow`
- [x] `flex-item-align`
- [x] `flex-line-pack`
- [x] `flex-negative`
- [x] `flex-order`
- [x] `flex-pack`
- [x] `flex-positive`
- [x] `flex-preferred-size`
- [x] `flex-shrink`
- [x] `flex-wrap`
- [x] `flex`
- [x] `font-family`
- [ ] `font-palette`
- [x] `font-size`
- [x] `font-stretch`
- [x] `font-style`
- [x] `font-variant-caps`
- [x] `font-weight`
- [x] `height`
- [ ] `image-rendering`
- [x] `inline-size`
- [x] `inset-block-end`
- [x] `inset-block-start`
- [x] `inset-block`
- [x] `inset-inline-end`
- [x] `inset-inline-start`
- [x] `inset-inline`
- [x] `inset`
- [x] `justify-content`
- [x] `justify-items`
- [x] `justify-self`
- [ ] `letter-spacing`
- [ ] `line-break`
- [x] `line-height`
- [ ] `list-style-image`
- [ ] `list-style-position`
- [ ] `list-style-type`
- [ ] `list-style`
- [x] `margin-block-end`
- [x] `margin-block-start`
- [x] `margin-block`
- [x] `margin-bottom`
- [x] `margin-inline-end`
- [x] `margin-inline-start`
- [x] `margin-inline`
- [x] `margin-left`
- [x] `margin-right`
- [x] `margin-top`
- [x] `margin`
- [ ] `marker-end`
- [ ] `marker-mid`
- [ ] `marker-side`
- [ ] `marker-start`
- [x] `mask-border-mode`
- [x] `mask-border-outset`
- [x] `mask-border-repeat`
- [x] `mask-border-slice`
- [x] `mask-border-source`
- [x] `mask-border-width`
- [x] `mask-border`
- [x] `mask-box-image-outset`
- [x] `mask-box-image-repeat`
- [x] `mask-box-image-slice`
- [x] `mask-box-image-source`
- [x] `mask-box-image-width`
- [x] `mask-box-image`
- [x] `mask-clip`
- [x] `mask-composite`
- [x] `mask-image`
- [x] `mask-mode`
- [x] `mask-origin`
- [x] `mask-position-x`
- [x] `mask-position-y`
- [x] `mask-position`
- [x] `mask-repeat`
- [x] `mask-size`
- [x] `mask-source-type`
- [x] `mask-type`
- [x] `mask`
- [x] `max-block-size`
- [x] `max-height`
- [x] `max-inline-size`
- [x] `max-width`
- [x] `min-block-size`
- [x] `min-height`
- [x] `min-inline-size`
- [x] `min-width`
- [x] `opacity`
- [x] `outline-color`
- [x] `outline-style`
- [x] `outline-width`
- [x] `outline`
- [x] `overflow-wrap`
- [x] `overflow-x`
- [x] `overflow-y`
- [x] `overflow`
- [x] `padding-block-end`
- [x] `padding-block-start`
- [x] `padding-block`
- [x] `padding-bottom`
- [x] `padding-inline-end`
- [x] `padding-inline-start`
- [x] `padding-inline`
- [x] `padding-left`
- [x] `padding-right`
- [x] `padding-top`
- [x] `padding`
- [ ] `perspective-origin`
- [x] `place-content`
- [x] `place-items`
- [x] `place-self`
- [x] `position`
- [x] `right`
- [x] `row-gap`
- [x] `scroll-margin-block-end`
- [x] `scroll-margin-block-start`
- [x] `scroll-margin-block`
- [x] `scroll-margin-bottom`
- [x] `scroll-margin-inline-end`
- [x] `scroll-margin-inline-start`
- [x] `scroll-margin-inline`
- [x] `scroll-margin-left`
- [x] `scroll-margin-right`
- [x] `scroll-margin-top`
- [x] `scroll-margin`
- [x] `scroll-padding-block-end`
- [x] `scroll-padding-block-start`
- [x] `scroll-padding-block`
- [x] `scroll-padding-bottom`
- [x] `scroll-padding-inline-end`
- [x] `scroll-padding-inline-start`
- [x] `scroll-padding-inline`
- [x] `scroll-padding-left`
- [x] `scroll-padding-right`
- [x] `scroll-padding-top`
- [x] `scroll-padding`
- [ ] `shape-rendering`
- [ ] `stroke-dasharray`
- [ ] `stroke-dashoffset`
- [ ] `stroke-linecap`
- [ ] `stroke-linejoin`
- [ ] `stroke-miterlimit`
- [ ] `stroke-opacity`
- [ ] `stroke-width`
- [ ] `tab-size`
- [ ] `text-align-last`
- [ ] `text-align`
- [x] `text-decoration-color`
- [ ] `text-decoration-line`
- [ ] `text-decoration-skip-ink`
- [ ] `text-decoration-style`
- [ ] `text-decoration-thickness`
- [ ] `text-decoration`
- [x] `text-emphasis-color`
- [ ] `text-emphasis-position`
- [ ] `text-emphasis-style`
- [ ] `text-emphasis`
- [ ] `text-indent`
- [ ] `text-justify`
- [x] `text-overflow`
- [ ] `text-rendering`
- [ ] `text-shadow`
- [ ] `text-size-adjust`
- [ ] `text-transform`
- [x] `top`
- [ ] `transform-box`
- [ ] `transform-origin`
- [ ] `transform-style`
- [ ] `transition-delay`
- [ ] `transition-duration`
- [ ] `transition-property`
- [ ] `transition-timing-function`
- [ ] `unicode-bidi`
- [ ] `user-select`
- [ ] `vertical-align`
- [ ] `view-transition-name`
- [x] `visibility`
- [ ] `white-space`
- [ ] `word-break`
- [ ] `word-spacing`
- [ ] `word-wrap`
- [x] `width`
- [ ] `z-index`

## Finish porting test suites

- [ ] From LightningCSS: https://github.com/parcel-bundler/lightningcss/blob/master/src/lib.rs
- [ ] From esbuild? https://github.com/evanw/esbuild/blob/main/internal/css_parser/css_parser_test.go

## Integration tests

We need integration tests that verify we can successfully parse and minify CSS from real-world libraries.

- [ ] Tailwind
- [ ] Shadcn
- [ ] Bootstrap
- [ ] DaisyUI
- [ ] Mantine
- [ ] Chroma
- [ ] Mui
- [ ] Antd
- [ ] PrimeFlex
- [ ] PrimeReact

## Optimize and profile

Performance should be faster than LightningCSS and esbuild. Currently, it's slightly slower than LightningCSS and missing features. We've done zero performance work so far. Performance will improve when we finish implementing the specific AST nodes for the properties and values.

**Comment by devongovett** [comment]
If you refuse to simply use Lightning CSS directly ([as I proposed in 2022](https://github.com/oven-sh/bun/issues/159#issuecomment-1208722409), and I am still open to helping with) and must copy my code instead, please at least consider contributing if you find bugs or opportunities for optimization. I have put thousands of hours of development effort into Lightning CSS in my spare time, so I would appreciate anything you could contribute back given that you are finding value in it. Thanks in advance.

**Comment by Jarred-Sumner** [comment]
@devongovett would love to + we're happy to do a monthly github sponsors donation

**Comment by romainmenke** [comment]
Also please be a good citizen and at least try to make a bundler that works the same as other CSS bundlers and respects the CSS specification.

Currently it only passes 12 out of 136 tests: https://github.com/romainmenke/css-import-tests

Either use something other than `@import` (as Sass does with `@use`) or follow the spec so that CSS authors can freely switch between tools or even having no tools at all.

**Comment by Jarred-Sumner** [comment]
> Also please be a good citizen and at least try to make a bundler that works the same as other CSS bundlers and respects the CSS specification.

Thank you for running the tests. This is part of why we call it “experimental” and it’s behind the —experimental-css flag — it’s not fully ready yet

**Comment by romainmenke** [comment]
I know it isn't ready yet :)
That is why I am reaching out here and now and sharing the test suite.
I am hoping that the finished thing will be compliant so that CSS authors gain a new tool that is helpful for them 🤞

**Comment by nicksrandall** [comment]
I'd really love it if CSS Modules support was included here!

See #16916
