### ISSUE TITLE
bake production build tracking issue

### ISSUE THREAD

**Issue by paperclover** [oven-sh/bun#14763]
Related issue for dev server #14324

I currently don't have a huge plan like I do for the dev server. Part of that is because most of the work is already done (use existing `bun build` code, server components work can be mostly reused). I will expand the list as I think of more tasks.

**High Level**

- [x] Static Build
    - [x] Prototype
    - [x] CSS Linking
    - [ ] Use multiple threads / VMs for static rendering.*
    - [x] Params
    - [ ] Implement static routers
- [ ] Non-static build
    - [ ] Serialized Router
    - [ ] Server runtime (likely a special property on Bun.serve)
        - [ ] Does anything need to be done with cache control headers?
    - [ ] Asset/Static file serving
    - [ ] `--compile` one server together

\*nice to have, not a strict blocker for 1.2

**For both static and non-static build**

- [ ] Bug: Runtime file  should be bundled for both client/server, instead of the client using the server build of it (which does not get written to disk)
- [X] Bug: SC Manifests need to contain output chunk names
- [ ] Identifier minification for SCB export names
- [ ] `separateSSRGraph: false`
- [ ] Plugins
- [ ] Verify it works on Windows

**API**

- [ ] Decide on entry file convention, currently `bun.app.ts`. maybe `bun.config.ts` or `bun.bake.ts`.
- [ ] `prerender` design choices. mainly around the idea of cancelation. need to think about non-static builds which if every route was known at bundle time, it is effectively static.
