### ISSUE TITLE
Implement case-changing utility methods

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#15087]
Example:
```ts
import {camelCase} from 'bun';

const camel = camelCase("hello world");
// "helloWorld"
```

#### TODO
- [ ] `Bun.camelCase("two words")` -> `"twoWords"`
- [ ] `Bun.capitalCase("two words")` -> `"Two Words"`
- [ ] `Bun.constantCase("two words")` -> `"TWO_WORDS"`
- [ ] `Bun.dotCase("two words")` -> `"two.words"`
- [ ] `Bun.kebabCase("two words")` -> `"two-words"`
- [ ] `Bun.pascalCase("two words")` -> `"TwoWords"`
- [ ] `Bun.snakeCase("two words")` -> `"two_words"`
- [ ] `Bun.trainCase("two words")` -> `"Two-Words"`

Like [`change-case`](https://github.com/blakeembrey/change-case/tree/main/packages/change-case)

#### Why?

This is useful for both `bun:sqlite` and `bun:sql`. We want to expose a way to convert column names from the version in the SQL query to what you want to use in your code.

This is a really common utility method otherwise.

If we need to build this for SQL clients, then we might as well expose it as a utility function in JS. We'll have to implement UTF-8, latin1, and UTF-16 versions regardless.

#### Implementation notes

It should probably be done in Zig, but it needs to accept a `comptime` parameter for output encoding so that it can be easily converted to a string for JS, or used in native code like for the SQL client. This means that it should support outputting as either a `[]const u8` or a `bun.String`.

#### Other notes

Briefly considered `Bun.string` as a namespace object to put these on, but the issue is we have `Bun.stringWidth` and it would be strange. I think keeping almost everything on the `Bun` global is nice since it can be both imported or used globally, and it's good for editor autocomplete to avoid namespaces. Our existing mechanism for lazy-loading functions makes this fine.

**Comment by paperdave** [comment]
also to consider `Bun.case.{camel/space/dot/pascal/etc}` or `Bun.changeCase.*` or even just `Bun.changeCase(phrase, case)`. no opinion on what is selected

the case conversion functions themselves should probably be generic on input and output types, like `fn (comptime From: type, comptime To: type, in: []From, out: []To) []To`

**Comment by nektro** [comment]
> This is useful to make title of article to URL alias for SEF (Search Engine Friendly). Nice to have if Bun supports a method which converts "việc làm" to "viec lam"

does this transformation have an existing name? it would likely involve converting  the string to [NFD Normalization Form](https://www.unicode.org/reports/tr15/#Normalization_Forms_Table) and then filtering any diacritic markers

**Comment by ippsav** [comment]
I can give this a try

**Comment by RiskyMH** [comment]
>  `Bun.constantCase("two words")` -> `"TWO_WORDS"`

I always thought it was officially called `SCREAMING_SNAKE_CASE`, but I can see this name as its usually for constants.

**Comment by truongan07** [comment]
> > This is useful to make title of article to URL alias for SEF (Search Engine Friendly). Nice to have if Bun supports a method which converts "việc làm" to "viec lam"
> 
> does this transformation have an existing name? it would likely involve converting the string to [NFD Normalization Form](https://www.unicode.org/reports/tr15/#Normalization_Forms_Table) and then filtering any diacritic markers

This transformation named "nfdCase". For example : 

```
const str = "PHẦN MỘT. LỊCH SỬ THẾ GIỚI THỜI NGUYÊN THỦY, CỔ ĐẠI VÀ TRUNG ĐẠI";
const newStr = str.normalize("NFD").replace(/[\u0300-\u036f]/g, "");

console.log(newStr);

const str1 = "Världens 100 största språk 2010";
const newStr1 = str.normalize("NFD").replace(/[\u0300-\u036f]/g, "");

console.log(newStr1);
```

**Comment by kravetsone** [comment]
Maybe add it to something like `Bun.changeCase.toCamel("")`?

**Comment by matt-user** [comment]
Is this issue still open?  I see a linked pr

**Comment by TiBianMod** [comment]
https://github.com/oven-sh/bun/pull/15097 , we have a pr ready to go!! cc @nektro

**Comment by ippsav** [comment]
@TiBianMod not sure if it's ready to go yet 100%, there is still some stuff related to utf8 encoding that i might have not handled properly,  though the functionality itself is working. Some feedback was shared a while back, but it didn’t move forward since other higher-priority stuff took over. I'd be happy to continue working on it if there is any feedback or things to be done

**Comment by ahmafi** [comment]
This would be great for combination with drizzle. The drizzle already has the `snake_case` support, but Bun should have it too, to be useful.

**Comment by martin-dimi** [comment]
Would love this feature too

**Comment by hjaber** [comment]
Did https://github.com/oven-sh/bun/commit/d7cf65eb0e7d05a65464eb17aeb32bf2009e7286 or https://github.com/oven-sh/bun/pull/15097 solve this issue?
