### ISSUE TITLE
Finish native `Buffer` implementation

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#155]
Bun's `Buffer` implementation is incomplete and I think it'd be good to have an issue where this is tracked. 

## `Buffer` static functions:
- [x] Buffer.alloc
- [x] Buffer.allocUnsafe
- [x] Buffer.allocUnsafeSlow
- [x] Buffer.byteLength
- [x] Buffer.compare
- [x] Buffer.concat
- [x] Buffer.from
- [x] Buffer.isBuffer
- [x] Buffer.isEncoding

## `Buffer.prototype` functions:
- [x] fill
- [x] includes
- [x] indexOf
- [x] lastIndexOf
- [x] swap16
- [x] swap32
- [x] swap64
- [x] asciiSlice
- [x] asciiWrite
- [x] base64Slice
- [x] base64urlSlice
- [x] base64urlWrite
- [x] base64Write
- [x] compare
- [x] copy
- [x] copy
- [x] equals
- [x] hexSlice
- [x] hexWrite
- [x] latin1Slice
- [x] latin1Write
- [x] readBigInt64BE
- [x] readBigInt64LE
- [x] readBigUInt64BE
- [x] readBigUInt64LE
- [x] readDoubleBE
- [x] readDoubleLE
- [x] readFloatBE
- [x] readFloatLE
- [x] readInt16BE
- [x] readInt16LE
- [x] readInt32BE
- [x] readInt32LE
- [x] readInt8
- [x] readUInt16BE
- [x] readUInt16LE
- [x] readUInt32BE
- [x] readUInt32LE
- [x] readUInt8
- [x] setBigUint64
- [x] slice
- [x] subarray
- [x] toJSON
- [x] toString
- [x] ucs2Slice
- [x] ucs2Write
- [x] utf16leSlice
- [x] utf16leWrite
- [x] utf8Slice
- [x] utf8Write
- [x] write
- [x] writeBigInt64BE
- [x] writeBigInt64LE
- [x] writeBigUInt64BE
- [x] writeBigUInt64LE
- [x] writeDoubleBE
- [x] writeDoubleLE
- [x] writeFloatBE
- [x] writeFloatLE
- [x] writeInt16BE
- [x] writeInt16LE
- [x] writeInt32BE
- [x] writeInt32LE
- [x] writeInt8
- [x] writeUInt16BE
- [x] writeUInt16LE
- [x] writeUInt32BE
- [x] writeUInt32LE
- [x] writeUInt8

## Bugs

- [x] `buffer.write(foo, "base64")` loses the last letter sometimes
- [ ] `buffer.write(foo, "base64url")` is too slow
- [x]  `Buffer.concat` in a tight loop is not yet faster than Node. I expect it to improve once pooling is added, but I don't think that's the entire story here. 

Once finished:
- [x] Port Node's tests for Buffer
- [x] `"buffer"` package should point to the native instance
- [x] `buffer.Blob` in `"buffer"` module should point to `globalThis.Blob`
- [x] `"crypto"` polyfill should use the native Buffer implementation

**Comment by myndzi** [comment]
Just an extra comment related to some of the other issues:

```js
console.log(Buffer.from('').constructor === Buffer);
console.log(Object.getPrototypeOf(Buffer.from('')).constructor === Buffer);
```

On Node.js, this will log "true" both times. In Bun it logs "false" both times. Obviously this is because Buffer in Bun is basically an API layered on top of Typed Arrays, but if you want full transparent parity, the constructors will need to be arranged correctly too.

(I just happened to stumble into this while doing something admitteddly a little weird)


... in Node, it appears to be the case that Buffer is simply a child of Uint8Array:
```
> Object.getPrototypeOf(Buffer.prototype) === Uint8Array.prototype
true
> Object.getPrototypeOf(Buffer) === Uint8Array
true
```

(edit) TIL how prototypes get set up when using "extends".

While Node seems to be [manually setting things up](https://github.com/nodejs/node/blob/main/lib/buffer.js#L349) rather than using "class" syntax, the net effect is equivalent to what you'd get by writing `class Buffer extends Uint8Array { ... }`.

Bun's Buffer, instead, appears to behave like `class Buffer {` (no extends), except its prototype has been pointed at Uint8Array's prototype

**Comment by asilvas** [comment]
List is incomplete.

```
readIntBE
readIntLE
writeIntBE
writeIntLE
```

**Comment by Jarred-Sumner** [comment]
@asilvas those functions will land in the next canary build (later tonight), thanks to @alexlamsl in #2341 (along with previously failing tests imported from Node.js that have been fixed)

The remaining todo here is to speed up `base64` and `base64url`, which is being tracked in https://github.com/oven-sh/bun/issues/2330
