### ISSUE TITLE
`Worker` & `worker_threads` stability tracking issue

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#15964]
When using `Worker` or `worker_threads` in Bun, I strongly suggest not calling `.terminate` or otherwise, ensuring they stay alive and reusing them instead of creating temporary ones and destructing them.

`Worker` in Bun is still marked as experimental. There are many different issues related to this. 

TODO:
- [x] https://github.com/oven-sh/bun/issues/5709
- [ ] Make all usages of `*JSC.EventLoop` use a weak pointer or an integer for the ScriptExecutionContextID, so that we do not attempt to reference an event loop of a closed Worker
- [ ] Have an easy way to force the closing state of all I/O related resources in Bun, so that writing tests for this stuff is trivial
- [ ] Ensure NAPI finalizers are handled correctly

**Comment by tracyloisel** [comment]
it making crashing our apps in production! very annoying! please fix asap

**Comment by aryanmotorq** [comment]
@Jarred-Sumner  if i had to create temporary workers and destroy them, if .terminate is unstable, is calling process.exit(0) inside the worker lead to more stability or both face the same issue of this

> Make all usages of *JSC.EventLoop use a weak pointer or an integer for the ScriptExecutionContextID, so that we do not attempt to reference an event loop of a closed Worker

**Comment by Jarred-Sumner** [comment]
it's the same underlying cause - the main issue here is the worker is terminating before everything depending on it gets a chance to handle that scenario. The JIT could still be compiling code in another thread. fetch() could be sending off a completed network request from the HTTP thread to the JavaScript thread. 

Secondarily, there are some issues where finalizers are executed unexpectedly and then we attempt to run JavaScript code inside of a finalizer which leads to a crash. But we've caught vast majority of these cases by now.

**Comment by aryanmotorq** [comment]
> it's the same underlying cause - the main issue here is the worker is terminating before everything depending on it gets a chance to handle that scenario. The JIT could still be compiling code in another thread. fetch() could be sending off a completed network request from the HTTP thread to the JavaScript thread.
> 
> Secondarily, there are some issues where finalizers are executed unexpectedly and then we attempt to run JavaScript code inside of a finalizer which leads to a crash. But we've caught vast majority of these cases by now.

So for now to just make it work, we can just let it finish it's event loop entirely, and let it terminate itself automatically. But it will leak memory as given in the checklist, so make sure to force Bun.gc collection on it as given here https://github.com/oven-sh/bun/issues/5709 

WIll this work?

**Comment by merlinaudio** [comment]
thank you for your reply :) i've considered doing this, but i fear it's not a great option for my use case.

i wonder what exactly triggers the crash i'm running into, as i couldn't find a minimal way to reproduce yet. i thought it may be my use of FinalizationRegistry, or Node-API/dylibs in the host process, but both seem to work fine in isolation.
