### ISSUE TITLE
Release blockers for v0.0.84

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#196]
- [ ] Fix reading 64-bit integers from JS <> Zig
- [ ] Improve test coverage for WebSockets
- [ ] Wire up HTTP server sink for SSR (WritableStream for HTTP)
- [ ] Fix broken HMR
- [ ] Add epoll to Poller (so reading a pipe from a stream in linux works)
