### ISSUE TITLE
Vite

### ISSUE THREAD

**Issue by brillout** [oven-sh/bun#250]
Vite is on [Bun's roadmap](https://github.com/Jarred-Sumner/bun/issues/159), which is awesome.

I'm opening this issue to track progress on Vite support.

A lot of Vite folks would gladly replace Node.js with Bun :-).

### Edit

Shameless plug: myself and @cyco130 are the authors of:
 - [HatTip](https://github.com/hattipjs/hattip) - a modern Express.js alternative: Fetch API / WinterCG standards + works anywhere (Node.js Edge, Deno, and Bun &mdash; of course 🙂).
 - [vite-plugin-ssr](https://vite-plugin-ssr.com/) - Like Next.js / Nuxt but as do-one-thing-do-it-well Vite plugin. (The production runtime works with Bun.)

**Comment by bluwy** [comment]
Tried Bun with Vite this weekend at https://github.com/bluwy/bun-vite-ts-test. Noted down some issues so far in the readme, with a patch to fix any fixable things so far. Currently stucked but I'll be watching Bun's releases and keep it up to date.

**Comment by brillout** [comment]
It's happening: https://twitter.com/jarredsumner/status/1551643885998247938.

**Comment by Jarred-Sumner** [comment]
As of Bun v0.1.11 (released today), here is the current status of the list of items mentioned in https://github.com/bluwy/bun-vite-ts-test 

> - [ ] http, http2, https not implemented.

The server parts of `http` are partially implemented - enough for `express` to work. `http2` and `https` aren't implemented at all yet

 - [x] `child_process` not implemented. Blocks esbuild.

> - [x] Regex negative lookbehind not supported in JSC. PITA to refactor.

This one is tricky. It's probably the biggest JSC-specific compatibility issue I've seen. We may need to have some WASM or ffi thing inserted by the transpiler to workaround it until https://bugs.webkit.org/show_bug.cgi?id=174931 is resolved, or attempt to implement it ourselves

- [x] When `const require = createRequire()` exists, bun treats the file as CJS, transpiling imports to `require()`, but because `const require` is declared late, it gives ` ReferenceError: Cannot access uninitialized variable`. Can be workaround by avoiding `require` and rename as `_require`. https://github.com/oven-sh/bun/issues/453

> - [ ] Dynamic `import()` doesn't execute file, as if a no-op. 

I'm not 100% sure what is happening in this case, but maybe it's a CommonJS module being dynamically imported? Normally, Bun's transpiler automatically calls .default() on CommonJS modules to initialize them, but it doesn't always do that for dynamic import currently.

> - [ ] ESM imports aren't hoisted.

Can you point to something that shows what this breaks? Sometimes people might use dynamic imports for lazy loading

- [x] `process.stdout` not implemented.
- [x] `path.posix` not implemented. Can be polyfilled with `path.posix = path` but works with posix env only.
- [x] `fileUrlToPath` doesn't accept `file://` strings. Can be fixed by wrapping `new URL(<string>)`.
- [x] `createRequire` doesn't work correctly with `file://` strings. URL however works correctly, and can be fixed by wrapping `new URL(<string>)`.
- [ ] `process` assignment like `process.env.NODE_ENV = '<string>'` shouldn't be replaced. Can be workaround by wrapping `eval()`.

> - [x] `performance` and `perf_hooks` not implemented. Can be polyfilled with `globalThis.performance`.

This is partially implemented, `performance.now()` exists but not `performance.mark()`, `performance.measure()`, nor the other Node-specific functions (they throw a not implemented error)

- [x] `self` not implemented. Can be polyfilled with `globalThis.self = globalThis`.
- [ ] `readline` not implemented.

**Comment by bluwy** [comment]
> > * [ ]  Dynamic `import()` doesn't execute file, as if a no-op.
> 
> I'm not 100% sure what is happening in this case, but maybe it's a CommonJS module being dynamically imported? Normally, Bun's transpiler automatically calls .default() on CommonJS modules to initialize them, but it doesn't always do that for dynamic import currently.

It's referring to [this line](https://github.com/vitejs/vite/blob/5d56e421625b408879672a1dd4e774bae3df674f/packages/vite/bin/vite.js#L44) where it's dynamically importing a file that should invoke and interpret the CLI args immediately to run the commands. Last I tested, dynamically importing it doesn't cause anything to happen. I had to do `import '../dist/node/cli.js'` at the top level instead to invoke it.

> > * [ ]  ESM imports aren't hoisted.
> 
> Can you point to something that shows what this breaks? Sometimes people might use dynamic imports for lazy loading

I don't remember where I saw this, but [here's an example](https://stackoverflow.com/a/29334761/13265944). This might be a rare and lower-priority case.

---

I haven't had the time to update https://github.com/bluwy/bun-vite-ts-test but thanks for keeping up with the improvements!

**Comment by leaanthony** [comment]
Really looking forward to this as it's a perfect fit for Wails: https://github.com/wailsapp/wails
How can someone who doesn't know Zig (yet) help with this? Would love to help out.

**Comment by Jarred-Sumner** [comment]
In canary (bun v0.5.1), Vite's dev server can start with some tweaks and load some files. **Overall: it doesn't work yet**, but we are getting close.

![image](https://user-images.githubusercontent.com/709451/213982761-27ce2056-578b-46e0-b067-d63360119201.png)

There is an issue preventing Vite's transform step from working consistently so files that need to be transpiled are not always transpiled. Specifically, the define plugin doesn't seem to work. It also has an issue loading the config file, but that's easy to work around since you can import typescript files in bun's runtime

My current hunch is a bug somewhere in path handling code in Bun. But I don't know yet

Some logs (the lines in `[bracket]` are internal debug logs in Bun)

```zig
[bun] poll(2) writable: true (4)
  vite:resolve 0.16ms /Users/jarred/Build/new-vite/vite-project/node_modules/vite/dist/client/env.mjs -> null +9ms
[SYS] write(2, 176) = 176
[FileSink] Wrote 176 bytes (fd: 2, head: 0, 0/11769)
[bun] poll(2) writable: true (4)
  vite:resolve 0.28ms @vite/env -> /Users/jarred/Build/new-vite/vite-project/node_modules/vite/dist/client/env.mjs +0ms
[SYS] write(2, 181) = 181
[FileSink] Wrote 181 bytes (fd: 2, head: 0, 0/11950)
[bun] poll(2) writable: true (4)
  vite:resolve 0.04ms /node_modules/vite/dist/client/env.mjs -> null +0ms
[SYS] write(2, 135) = 135
[FileSink] Wrote 135 bytes (fd: 2, head: 0, 0/12085)
[bun] poll(2) writable: true (4)
  vite:import-analysis 1.61ms [1 imports rewritten] node_modules/vite/dist/client/client.mjs +5ms
[SYS] write(2, 160) = 160
[FileSink] Wrote 160 bytes (fd: 2, head: 0, 0/12245)
[bun] poll(2) writable: true (4)
  vite:transform 17.95ms /@vite/client +5ms
[SYS] write(2, 93) = 93
[FileSink] Wrote 93 bytes (fd: 2, head: 0, 0/12338)
[bun] poll(2) writable: true (4)
  vite:time 22.58ms /@vite/client +5ms
[SYS] write(2, 88) = 88
[FileSink] Wrote 88 bytes (fd: 2, head: 0, 0/12426)
[Server] deinitIfWeCan
[SYS] open(/node_modules/vite/dist/client/env.mjs): -1
Failed to load url /node_modules/vite/dist/client/env.mjs (resolved id: /node_modules/vite/dist/client/env.mjs). Does the file exist?
[Loop] unref x 2
[SYS] open(/node_modules/vite/dist/client/env.mjs): -1
[SYS] stat(/Users/jarred/Build/new-vite/vite-project/node_modules/vite/dist/client/env.mjs) = 0
[bun] poll(2) writable: true (4)
  vite:time 1.17ms /node_modules/vite/dist/client/env.mjs +4ms
[SYS] write(2, 112) = 112
[FileSink] Wrote 112 bytes (fd: 2, head: 0, 0/12538)
[Server] deinitIfWeCan
[SYS] stat(/Users/jarred/Build/new-vite/vite-project/node_modules/vite/dist/client/env.mjs.map) = 0
[SYS] open(/Users/jarred/Build/new-vite/vite-project/node_modules/vite/dist/client/env.mjs.map): 123
n @ fs.ReadStream.#internalRead, after clamp 65536
[SYS] fstat(124) = 0
[SYS] read(124, 65536) = 1797 (0.009ms)
n @ fs.ReadStream.#internalRead, after clamp 65536
[bun] poll(2) writable: true (4)
  vite:time 2.41ms /node_modules/vite/dist/client/env.mjs.map +7ms
[SYS] write(2, 116) = 116
[FileSink] Wrote 116 bytes (fd: 2, head: 0, 0/12654)
[SYS] close(124)
[Server] deinitIfWeCan
[SYS] stat(/Users/jarred/Build/new-vite/vite-project/public/vite.svg) = 0
[SYS] open(/Users/jarred/Build/new-vite/vite-project/public): 124
[SYS] close(124)
[bun] poll(2) writable: true (4)
  vite:time 0.34ms /vite.svg +2ms
[SYS] write(2, 83) = 83
[FileSink] Wrote 83 bytes (fd: 2, head: 0, 0/12737)
[Server] deinitIfWeCan
[bun] poll(2) writable: true (4)
  vite:html-fallback Rewriting GET / to /index.html +47s
```

<img width="720" alt="image" src="https://user-images.githubusercontent.com/709451/213982465-234e2800-8422-44a0-9474-808ddb43de01.png">

**Comment by cyco130** [comment]
> My current hunch is a bug somewhere in path handling code in Bun. But I don't know yet

When trying to make Rakkas (a Vite-based React metaframework) run on Deno, I encountered a similar problem. My current workaround is a [small plugin](https://github.com/rakkasjs/deno-template/blob/943ea22e8575ec97e7e2b23e3a5c0ef7aff1d3b4/vite.config.mts#L11) to help Vite resolve its client and env entries.

Vite tries to resolve their full path based on the location of its `package.json` file which [it computes](https://github.com/vitejs/vite/blob/f72fdc7c995db502ca89f0057cfc1fcd6660212f/packages/vite/src/node/constants.ts#L81) using `import.meta.url`. Any incompatibility with the exact paths causes it to miss them. In Deno, it's because of how it links packages: `import.meta.url` doesn't return the same string as Vite's resolver does so it needs a hand from my little plugin.

Just my two cents, maybe it's related.

**Comment by saolof** [comment]
How does the move towards SWC in Vite 4.0 affect bun support?

**Comment by intrnl** [comment]
> How does the move towards SWC in Vite 4.0 affect bun support?

Just to be clear, Vite 4.0 isn't moving to SWC, it's the React plugin that now has an alternative version using SWC. In any case, you can always fallback to the slower Babel version if it doesn't work.

**Comment by mnik01** [comment]
Any news here?

**Comment by ThatOneBro** [comment]
> Any news here?

There's still some bugs preventing Vite from fully working, however we are working on stabilizing our Node APIs currently and it may end up working after some more big fixes we're working on. Stay tuned

**Comment by Jarred-Sumner** [comment]
I think it's important for Vite to not only work in Bun (it doesn't yet), but to be faster in Bun than other runtimes. 

One of the reasons why we are building a new bundler (https://github.com/oven-sh/bun/pull/2312) is to help make that happen.

**Comment by pooledge** [comment]
Sorry folks, I couldn't find better issue to fit this into...

_Edited: created a new issue. My apologies._

**Comment by controversial** [comment]
> I couldn't find better issue to fit this into

@pooledge you should open a new issue or discussion; this issue is tracking general support for Vite

**Comment by paperclover** [comment]
The vite dev server is close to working. Here are the known blockers:

- #832 (for any hmr to work)
- #3216 (breaks loading config files)

For using SvelteKit on top of this I've also found:

- #3225 

I'm sure there will be a few more bugs after fs.watch is implemented, as the bulk of a dev server is in it's ability to re-build code.

Also, for what it's worth, running an http stress test on the dev server shows Bun can handle 1.9x as many requests on average compared to node. This isn't really that significant because stress testing a dev server is pretty useless, but hey... it's there.

**Comment by aarjithn** [comment]
Would be nice if this comes in at v1.0 @Jarred-Sumner

**Comment by Jarred-Sumner** [comment]
> Would be nice if this comes in at v1.0 @Jarred-Sumner

how about tomorrow in Bun v0.7? https://github.com/vitejs/vite/pull/13901

**Comment by brillout** [comment]
💯 Very much looking forward to it, especially if it solves the countless ESM-CJS compatibility issues (it's a *massive* pain for users). Looking forward to a bright Bun + Vike (upcoming vite-plugin-ssr rebrand) future.

**Comment by birkskyum** [comment]
It seems like [`require('u' + 'rl')`](https://github.com/vitejs/vite/blob/d991d7d43e657d66f9aca7fb72f7be79b9e08699/packages/vite/src/node/build.ts#L1106) in Vite breaks when trying to run SolidStart with the latest canary 0.7. 

Error: `Cannot find package "u" from [...]/vite/dist/node-cjs/publicUtils.cjs`

**Comment by gitblit** [comment]
I reported #3705 but am unsure if this is a Bun or Vite issue. It may even be a duplicate, if so, apologies.

**Comment by Jarred-Sumner** [comment]
> I reported #3705 but am unsure if this is a Bun or Vite issue. It may even be a duplicate, if so, apologies.
> It seems like [`require('u' + 'rl')`](https://github.com/vitejs/vite/blob/d991d7d43e657d66f9aca7fb72f7be79b9e08699/packages/vite/src/node/build.ts#L1106) in Vite breaks when trying to run SolidStart with the latest canary 0.7.
> 
> Error: `Cannot find package "u" from [...]/vite/dist/node-cjs/publicUtils.cjs`

Both of these should be fixed in canary (please leave a comment if you see that still)


The current blockers for SolidStart:
- Dependency on node's --experiemntal-vm-modules flag
- Event loop bug causing the process to exit prematurely while loading `es-module-loader`

**Comment by birkskyum** [comment]
I can confirm that for SolidStart (0.2.27, released some hours ago) instead of an error, it now just exit early as you say, using either node / bun adapter. @Jarred-Sumner , am I right to assume both of these issues requires changes to SolidStart rather than Bun?

**Comment by gitblit** [comment]
I just updated to latest canary. Looks like the problem persists.
<img width="582" alt="image" src="https://github.com/oven-sh/bun/assets/868217/f27d39ee-6b10-442a-8b3c-6d9ba20854d6">

**Comment by paperclover** [comment]
Vite support has been landed in 0.7, closing this issue. Note that you need the latest version of Vite as there was a small patch in their code to fix WebSocket/HMR.

SvelteKit does not work due to worker_threads not being implemented.

**Comment by mreduar** [comment]
🎉🎉

**Comment by paperclover** [comment]
We'll be tracking SvelteKit specific support in #600, and SolidStart in #3736.

Please open a separate issue (if it doesnt exist) for other frameworks.

**Comment by chakrihacker** [comment]
Can we have some love for parcel??

**Comment by intrnl** [comment]
if it doesn't work, make a new issue

**Comment by Jarred-Sumner** [comment]
I’m so happy we shipped this

**Comment by brillout** [comment]
Can't wait for a rock-solid Bun ⛰️

**Comment by cn3c3p** [comment]
Support Quasar?

**Comment by Anubarak** [comment]
> Vite support has been landed in 0.7, closing this issue. Note that you need the latest version of Vite as there was a small patch in their code to fix WebSocket/HMR.
> 
> SvelteKit does not work due to worker_threads not being implemented.

~~I have the latest version of Vite and Bun but HMR does not work. In fact when I run~~
```
bunx --bun vite
```

~~from https://bun.sh/guides/ecosystem/vite my index.js does not change at all. I need to manually restart the server after every single change. Was that ever an issue for you? Maybe this is a WLS issue on my machine~~

Edit: never mind, sorry there is already an issue for this

**Comment by UnknownH** [comment]
> I think it's important for Vite to not only work in Bun (it doesn't yet), but to be faster in Bun than other runtimes.
> 
> One of the reasons why we are building a new bundler (#2312) is to help make that happen.

Does this mean Vite can also bundle using bun now, instead of esbuild?
