### ISSUE TITLE
Support Next.js 13 in Bun 

### ISSUE THREAD

**Issue by Jarred-Sumner** [oven-sh/bun#3776]
Known major blockers:
- [x] Submit PR to next to use bun's `undici` override (instead of a prebundled version) in Bun
- [x] Submit PR to next to use bun's `ws` override (instead of a prebundled version) in Bun
- [x] jest-worker needs to work, which depends on child_process.fork(). possibly worker_threads
- [ ] Fix any napi bugs uncovered when testing Turbopack

The first issue is here:
```js
17 | class NotImplementedError extends Error {
18 |   code;
19 |   constructor(feature, issue) {
20 |
21 |     super(feature + " is not yet implemented in Bun." + (issue ? " Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/" + issue : ""));
       ^
NotImplementedError: node:diagnostics_channel is not yet implemented in Bun. Track the status & thumbs up the issue: https://github.com/oven-sh/bun/issues/2688
 code: "ERR_NOT_IMPLEMENTED"

      at new NotImplementedError (node:diagnostics_channel:21:4)
      at throwNotImplemented (node:diagnostics_channel:8:8)
      at channel (node:diagnostics_channel:30:2)
      at 4822 (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:2:163873)
      at __nccwpck_require__ (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:13952)
      at 4475 (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:6547)
      at __nccwpck_require__ (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:13952)
      at 9002 (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:1:27356)
      at __nccwpck_require__ (/Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:13952)
      at /Users/jarred/Build/nexty/node_modules/next/dist/compiled/undici/index.js:3:14201
```

Bun has a builtin polyfill for "undici" which uses the globals for `fetch`, `Request`, etc instead of a JS implementation. When run in Bun, next should use that. The same for `"ws"`.

**Comment by Jarred-Sumner** [comment]
cc @timneutkens @leerob

**Comment by controversial** [comment]
Congrats to the Bun team on shipping this! :‍)

Note that that running `bun --bun next dev` still errors for apps using middleware, blocked on #5648 (see #9447)

**Comment by kapitche** [comment]
> Congrats to the Bun team on shipping this! :‍)
> 
> Note that that running `bun --bun next dev` still errors for apps using middleware, blocked on #5648 (see #9447)

Indeed been trying to push this issue for months because otherwise bun is not production ready to work with under nextjs14

**Comment by ebidel** [comment]
Anyone else seeing high CPU usage when running the next dev server with `bun --bun next dev`? This is refreshing the page a few times:

<img width="609" alt="Screenshot 2024-04-03 at 3 02 44 PM" src="https://github.com/oven-sh/bun/assets/238208/23268408-47bf-4710-a6f6-3653afc66107">

**Comment by kapitche** [comment]
> Anyone else seeing high CPU usage when running the next dev server with `bun --bun next dev`? This is refreshing the page a few times:
> 
> 
> 
> <img width="609" alt="Screenshot 2024-04-03 at 3 02 44 PM" src="https://github.com/oven-sh/bun/assets/238208/23268408-47bf-4710-a6f6-3653afc66107">
> 
> 

Personally I can't even run it because am I using nextjs 14 middleware
