### ISSUE TITLE
express support

### ISSUE THREAD

**Issue by evanwashere** [oven-sh/bun#496]
required to make express work:
- [x] polyfill require('depd')
- [x] fix require('iconv-lite');
- [x] fix require('object-inspect')
- [x] polyfill require('node:net').isIP
- [x] polyfill require('node:http') apis
- [x] polyfill setImmediate (used by express)

optional:
- [ ] polyfill require('node:https') apis
- [ ] polyfill Error.captureStackTrace (only used by depd)

express bugs:
- [ ] router misbehaving (calls `app.get('/')` handler but returns `Cannot get /` page)

fixes #405

**Comment by prolaxu** [comment]
when i tried to run express :
i found  https://github.com/oven-sh/bun/issues/747
with error Cannot found module "./utils.inspect"
and then i tried  putting __dirname in front of "./utils.inspect" the issue is solved
it means some how bun is failed to import js file  of same dir after issue solved another issue occurred
![Screenshot from 2022-07-18 12-10-28](https://user-images.githubusercontent.com/54370052/179459529-a0e85aa9-d92b-4045-b99c-3c52e8d432bc.png)

here is error on line no 43
![Screenshot from 2022-07-18 12-52-27](https://user-images.githubusercontent.com/54370052/179460314-c9f5960a-cee4-4d61-ac78-2b24cd3157b2.png)

**Comment by adamjosefus** [comment]
Function `setImmediate` is part of many packages too. For example: https://www.npmjs.com/package/glob

**Comment by Bellisario** [comment]
Seems there is a problem with [Oak](https://github.com/oakserver/oak#nodejs), too.
I tried using it because it was born for Deno, that should have similar web request/response API of Bun, but that's not so.

Anyone knows a library working with Bun that makes simple make servers like Express or Oak?

**Comment by adamjosefus** [comment]
@Bellisario Try look for this https://github.com/apvarun/awesome-bun. Hope it helps

**Comment by Bellisario** [comment]
Thanks @adamjosefus, this helps!!!

Maybe for now I'll use [Bao.js](https://github.com/mattreid1/baojs), seems it's very similar to Express and Oak!

**Comment by 0x4a61636f62** [comment]
> when i tried to run express : i found #747 with error Cannot found module "./utils.inspect" and then i tried putting __dirname in front of "./utils.inspect" the issue is solved it

This worked for me too although there are some follow-up issues.

**Comment by paperclover** [comment]
i just want to comment that as of 0.1.7, express slightly works, but i want to note that this code doesn't work yet.
```ts
import express from 'express';

const app = express();
app.get('/', (req, res) => {
  res.send('Hello World!'); // wont cause the response to end, which will hang any client requests. calling .end fixes it.
});
app.listen(3000, () => {
  console.log('http://localhost//3000!');
});
```

**Comment by frodoe7** [comment]
Any updates for that issue
would like to use express with bun

**Comment by zhuzilin** [comment]
> Any updates for that issue
> would like to use express with bun

The above example works in v0.1.10, you could give it a try :)

**Comment by Bellisario** [comment]
@evanwashere I found an https polyfill, it uses the http module, which is already polyfilled:
https://github.com/substack/https-browserify/blob/master/index.js

I can't help more because I'm not a Zig programmer, but I'm ready for any other JS/TS help!

**Comment by Jarred-Sumner** [comment]
This is fixed
