### ISSUE TITLE
Implement commands in Bun shell

### ISSUE THREAD

**Issue by Electroid** [oven-sh/bun#9716]
This is a tracking issue for commands that we should implement as builtins in the Bun shell. Some of these are taken from [GNU coreutils](https://en.wikipedia.org/wiki/List_of_GNU_Core_Utilities_commands).

- [x] `cat`
- [x] `touch`
- [x] `mkdir`
- [x] `cd`
- [x] `echo`
- [x] `pwd`
- [x] `which`
- [x] `rm`
- [x] `mv`
- [x] `ls`
- [x] `exit`
- [x] `true`
- [x] `false`
- [x] `cp`
- [ ] `timeout`
- [x] `yes`
- [x] `basename`
- [ ] `realpath`
- [x] `dirname`
- [ ] `mktemp`
- [ ] `truncate`
- [ ] `head`
- [ ] `tail`
- [ ] `cut`
- [ ] `uniq`
- [x] `seq`
- [ ] `sleep`
- [ ] `tee`
- [ ] `date`
- [ ] `sha1sum`
- [ ] `sha224sum`
- [ ] `sha256sum`
- [ ] `sha384sum`
- [ ] `sha512sum`
- [ ] `md5sum`
- [ ] `sort`
- [ ] `printenv`
- [ ] `env`
- [ ] `whoami`
- [ ] `who`
- [ ] `uptime`

This is not an exhaustive list, we can add commands as we think it's a good idea to implement.

While these will already be generally available on most posix systems, having them in the Shell will also allow them to be readily available on Windows when using Bun Shell.

**Comment by edimarlnx** [comment]
I want to create a bun shell to use instead of bash, zsh, sh, etc.
I started the simple [project](https://github.com/edimarlnx/bun-shell/blob/main/bunsh) to think about how it is possible.

So, I have some questions:
1. Is there a way to register a shell command using Javascript definition?

For example:

```js
$.register('add', (n1,n2) => {
  return n1+n2; 
}) 

$`add 2 5`
```

2. Is there a way to persist changes into shell "session"?

For example: 
When I use the command $`cd DIRNAME`, the work directory of the shell ($) changes to the new directory. 

If these examples are possible, It will do a powerful to make a great shell alternative using Javascript.

**Comment by thewh1teagle** [comment]
It will be cool if `Bun` will support cross platform `unzip` for `zip, 7z` etc, and cross platform `wget` or similar which download a file (`Windows` doesn't have `wget` by default) and using fetch for download is slow.

**Comment by LifeJustDLC** [comment]
#10174 update `cp`
With the power of `cp`, I can finally write some cross platform readable building scripts, to copy my `manifest.json` to `dist`. 😂

**Comment by mlkt** [comment]
Why not implement the `exec` command? Executing it to replace the current process is a crucial and convenient command.

**Comment by Ptitet** [comment]
Is it possible to add the `wc` command ? It is not available on Windows.

**Comment by rametta** [comment]
`sed` command would really be helpful too. find and replace is something I need often

**Comment by 7flash** [comment]
It works well with running any of my scripts like

await $`script.py ${args}`.quiet();

Therefore I'm sure there must be a simple way to make it work with all installed programs like "curl" in example above

**Comment by maxwellb** [comment]
Wishlisting

- [x] `if` / `then` / `else` / `elif` / `fi` (undocumented)
- [ ] `[` / `]` / `test` (will run from PATH if found)
  - [ ] operators ` `, `( )`, `!`, `-n`, `-z`, `=`, `!=`, `-e`, `-f`, `-d`, `-r`
- [x] `&&` (undocumented)
- [x] `||` (undocumented)
- [ ] read
- [ ] declare
  - [ ] `-p`
  - [ ] (not wishlisting attributes)
- [ ] `while`, `do`, `break`, `done`
- [ ] cat (builtin)

```
$ cat > bun.sh
while true ; do echo YARP ; break ; done

$ source bun.sh
YARP

$ env -i `which bun` bun.sh
bun: command not found: while
bun: command not found: do
bun: command not found: break
bun: command not found: done

$ cat > bun.sh
echo BAR | ( read FOO ; echo ${FOO} )

$ source bun.sh
BAR

$ env -i `which bun` bun.sh
bun: command not found: read

${FOO}

$ cat > bun.sh
echo BAR | ( readzzz FOO ; echo ${FOO} )

$ unset FOO

$ source bun.sh
readzzz: command not found

$ env -i `which bun` bun.sh
bun: command not found: readzzz
${FOO}

$ cat > bun.sh
readlink -f bun.sh

$ source bun.sh
/srv/apps/bun.sh

$ env -i `which bun` bun.sh
bun: command not found: readlink

$ bun bun.sh
/srv/apps/bun.sh

$ cat > bun.sh
cat bun.sh

$ source bun.sh
cat bun.sh

$ env -i `which bun` bun.sh
bun: command not found: cat

~$

```

**Comment by maxwellb** [comment]
> unfortunately, curl not working with bun shell
> 
> ```
> import { $ } from 'bun';
> 
> async function main() {
>   const url = "https://jsonplaceholder.typicode.com/todos/1";
> 
>   const curlCommand = `curl -X GET ${url}`;
> // [...]
> ```
> 
> throws an error
> 
> > bun: command not found: /usr/bin/curl -X GET https://jsonplaceholder.typicode.com/todos/1

This seems to be due to the fact that any interpolated value is passed as a single argument to the tag function. Much like if you surrounded the whole command in quotes in your shell.

To work around this @7flash you can leverage xargs if it is on your PATH:

```
import { $ } from 'bun';

async function main() {
  const url = "https://jsonplaceholder.typicode.com/todos/1";

  const curlArgs = `-X GET ${url}`;

  try {
    const result = await $`echo ${curlArgs} | xargs curl`;

    if (result.exitCode !== 0) {
      console.error(`Curl command failed with exit code ${result.exitCode}`);
      process.exit(1);
    }

    console.info(`Curl command succeeded with output:`);
    console.info(result.stdout);
  } catch (error) {
    console.error(`Request failed: ${error.message}`);
    process.exit(1);
  }
}

main();
```

```
$ bun bun.js
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    83  100    83    0     0    679      0 --:--:-- --:--:-- --:--:--   680
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}Curl command succeeded with output:
<Buffer 7b 0a 20 20 22 75 73 65 72 49 64 22 3a 20 31 2c 0a 20 20 22 69 64 22 3a 20 31 2c 0a 20 20 22 74 69 74 6c 65 22 3a 20 22 64 65 6c 65 63 74 75 73 20 61 ... 33 more bytes>

```

**Comment by XaveScor** [comment]
Hello guys. What do you think just take https://github.com/uutils/coreutils instead of your own fork. I think it is not a problem right now because of the port to Rust
